#!/static/ash

PATH=/static

kernel_version_=`uname -r`

modules_to_load_=$(/static/discover --disable-bus all --enable-bus pci --type network --normalize-whitespace --data-path=linux/module/name --data-version=$kernel_version_)

if [ $? -ne 0 ]; then
  echo "Error: discover returned an error while discovering the appropriate nic module"
  echo "$modules_to_load_"
  return 1
fi

echo $modules_to_load_ | grep -v '^ $' | uniq
return 0
